### PR TITLE
Exit container with helpful error message when pseudo tty is missing

### LINKED ISSUE #139: Problem with new version 2.2.0-amd64-alpine
I want to upgrade version of the container but i have the next problem

`
openhab_develop | Hit '<tab>' for a list of available commands
openhab_develop | and '[cmd] --help' for help on a specific command.
openhab_develop | Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown openHAB.
openhab_develop | 
openhab_develop | openhab> Error executing command: java.lang.NullPointerException
`

Where can i see more information?

### PR DESCRIPTION
**Pull request by wborn**
Fixes #139 and #140

Successfully tested this with debian and alpine on amd64.

I've also converted the Windows line endings to Unix line endings in update.sh otherwise the script would not run on Ubuntu.

Can you please review this @cniweb, @smerschjohann or @martinvw?

---
This change is [Reviewable](https://reviewable.io/reviews/openhab/openhab-docker/141)

### CODE REVIEW

**Comment by wborn** [comment]
It seems I have to make Travis happy again!

**Comment by cniweb** [comment]
@watou I think you must change the docker run command for travis:
https://github.com/openhab/openhab-docker/blob/master/.travis.yml#L14

**Comment by wborn** [comment]
Thanks for the pointer @cniweb . Since all builds failed it seems to work properly! ;-)

**Comment by wborn** [comment]
Travis now seems to have issues downloading from launchpad :-(

```
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/InRelease  
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/InRelease  
W: Failed to fetch http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu/dists/trusty/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/Release.gpg  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/Release.gpg  Unable to connect to ppa.launchpad.net:http:
```

**Comment by cniweb** [comment]
https://travis-ci.org/openhab/openhab-docker/jobs/319914102#L352
???

**Comment by wborn** [comment]
Yes very strange. I'll squash, rebase and fix the merge conflicts and see what happens.

**Comment by wborn** [comment]
@cniweb the check now uses `test -t 0` which works with Travis.

I think Travis is using Vagrant (by HashiCorp) which has some tty issues, see:

* https://github.com/hashicorp/vagrant/issues/1673
* https://github.com/hashicorp/vagrant/issues/7597
  
HashiCorp makes fun of this issue at their [homepage](https://www.hashicorp.com/).
At the bottom of the page it says `stdin: is not a tty` in their footer :smile:

HTML source:
```html
<div class="not-a-bug">
<span data-text="This is not a bug on the website, but rather an inside joke for some of our oldest customers." title="No, this is not a bug">
stdin: is not a tty
</span></div>
```

**Comment by cniweb** [comment]
:lgtm:

---

Review status: 0 of 44 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openhab/openhab-docker/141#-:-L0vZSNOttPP0fK9SQWV:bnfp4nl)*

**Comment by cniweb** [comment]
Reviewed 44 of 44 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openhab/openhab-docker/141)*

**Comment by martinvw** [comment]
LGTM ;-)

**Pull request merged**
