### PR TITLE
Add JCE Policy

### LINKED ISSUE #118: Kind request to include Java8 unlimited JCE policy extension into openhab docker image
Hi there,
first of all thank you for providing an official openhab docker image!!!
I experience an issue with the binding for my heating (Buderus KM200) that requires the Java8 extension for unlimited JCE policy to allow longer hashes for password strings to be able to read and decode the data coming from the gateway. Probably this issue does not only affect me with the KM200 binding but also other bindings that use today resp. will use in the future longer hash strings for authentication as supported with the standard version of Java.
Even though JCE is included in the docker image it does not work correctly. Please find below the error I get in the openhab.log:

> 22:54:07.169 [INFO ] [.binding.km200.internal.KM200Binding] - Update KM200 Binding configuration, it takes a minute....
> 2017-10-30 22:54:07.178 [INFO ] [.binding.km200.internal.KM200Binding] - Starting communication test..
> 2017-10-30 22:54:07.446 [INFO ] [.binding.km200.internal.KM200Binding] - Received data..
> 2017-10-30 22:54:07.460 [ERROR] [hab.binding.km200.internal.KM200Comm] - Exception on encoding: {}
> java.security.InvalidKeyException: Illegal key size or default parameters
> 	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1026)[:1.8.0_144]
> 	at javax.crypto.Cipher.implInit(Cipher.java:801)[:1.8.0_144]
> 	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)[:1.8.0_144]
> 	at javax.crypto.Cipher.init(Cipher.java:1249)[:1.8.0_144]
> 	at javax.crypto.Cipher.init(Cipher.java:1186)[:1.8.0_144]
> 	at org.openhab.binding.km200.internal.KM200Comm.decodeMessage(KM200Comm.java:260)[183:org.openhab.binding.km200:1.10.0]
> 	at org.openhab.binding.km200.internal.KM200Binding.updated(KM200Binding.java:161)[183:org.openhab.binding.km200:1.10.0]
> 	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1461)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1417)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:141)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:109)[3:org.apache.felix.configadmin:1.8.12]
> 	at java.lang.Thread.run(Thread.java:748)[:1.8.0_144]
> 2017-10-30 22:54:07.466 [ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.cm.ManagedService, org.osgi.service.event.EventHandler, id=292, bundle=183/mvn:org.openhab.binding/org.openhab.binding.km200/1.10.0]: Unexpected problem updating configuration org.openhab.km200
> java.lang.RuntimeException: Decoding of the KM200 message is not possible!
> 	at org.openhab.binding.km200.internal.KM200Binding.updated(KM200Binding.java:163)[183:org.openhab.binding.km200:1.10.0]
> 	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1461)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1417)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:141)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:109)[3:org.apache.felix.configadmin:1.8.12]
> 	at java.lang.Thread.run(Thread.java:748)[:1.8.0_144]
> 

I did some research what is needed for JCE and found the following to JAR files need to be installed in the docker image. The files are called **local_policy.jar** and **US_export_policy.jar** and they are in the image as shown below:

> root@openhab-openhab220:/usr/lib/java-8/jre/lib/security# ls -l
> total 236
> -rw-rw-r-- 1 31450 31450 1273 Jul 26 14:24 blacklisted.certs
> -rw-rw-r-- 1 31450 31450 186962 Jul 26 14:24 cacerts
> -rw-rw-r-- 1 31450 31450 2466 Jul 26 14:24 java.policy
> -rw-rw-r-- 1 31450 31450 34688 Jul 26 14:24 java.security
> -rw-rw-r-- 1 31450 31450 1040 Jul 26 14:24 local_policy.jar
> -rw-rw-r-- 1 31450 31450 620 Jul 26 14:24 US_export_policy.jar
> root@openhab-openhab220:/usr/lib/java-8/jre/lib/security#

I don't get errors and it works with the wetware/openhab docker image which uses OpenJDK 1.8.0.45 with JCE and the JDK used in your official openhab image is 1.8.0_144 and has also the JCE files. Hence there must be the difference in the Java versions and/or probably in the Java default configuration.

I would prefer much more to use your official image as some cloned one.
Hence I kindly ask you to consider my issue!

### PR DESCRIPTION
**Pull request by cniweb**
Fix #118

---
This change is [Reviewable](https://reviewable.io/reviews/openhab/openhab-docker/138)

### CODE REVIEW

**Comment by cniweb** [comment]
@wborn

**Comment by wborn** [comment]
Did you also have a look at the license and terms under which the JCE is provided?
https://www.azul.com/products/zulu-and-zulu-enterprise/zulu-cryptography-extension-kit/

**Comment by smerschjohann** [comment]
I think it's fine, as the openjdk version does not have such restrictions in the first place.

Germany and many other countries do not have such export/import restrictions. But nonetheless, it might be a good idea to provide a version without unlimited jce for the 0.1% who might otherwise do something illegal in their country. But I would default to unlimited.

**Comment by smerschjohann** [comment]
See https://en.m.wikipedia.org/wiki/Restrictions_on_the_import_of_cryptography#Status_by_country for further information on countries with import restrictions

**Comment by martinvw** [comment]
But its fair question, see also:

> To download the Zulu® CEK, you must first acknowledge its Terms of Use (reference below). After download, review the supplied README.txt file for instructions on applying the Zulu® CEK.

We just more or less skip the step and never mention anything about that when downloading the docker image.

@kaikreuzer do you have an opinion about this?
@ThomDietrich did you do something with this in openhabian?

**Comment by wborn** [comment]
> it might be a good idea to provide a version without unlimited jce for the 0.1% who might otherwise do something illegal in their country. But I would default to unlimited.

Since the ZuluJCEPolicies.zip is just a 12kB download another way could be to add an environment variable that the user sets when agreeing to the [Zulu terms](https://www.azul.com/products/zulu-and-zulu-enterprise/zulu-cryptography-extension-kit/). Then when the image is started the entrypoint script checks the variable and downloads and extracts the ZIP when necessary.

**Comment by cniweb** [comment]
@wborn That's a good idea, could you rebuild that?

**Comment by wborn** [comment]
@cniweb I can have a look when we agree this is the way to go and when I find some time for this. :wink:

**Comment by martinvw** [comment]
@wborn I agree and I'm sure that @kaikreuzer also would prefer a way that everyone can use the openHAB docker legally in his part of the world :-)

**Comment by kaikreuzer** [comment]
Definitely so 👍

**Comment by ThomDietrich** [comment]
@martinvw the CEK came up for openHABian but is not included yet: https://github.com/openhab/openhabian/issues/111

**Comment by martinvw** [comment]
Thanks for the update an extra reason to pay attention to it. @wborn how are you doing still willing to help us out here :-)

**Comment by wborn** [comment]
Yes I'll take a look now the container upgrade PR has been merged which would have caused a lot of merge issues!

**Pull request merged**
