### PR TITLE
Add 2.3.0 and 2.4.0-snapshot versions

### PR DESCRIPTION
**Pull request by wborn**
Adds the 2.3.0 and 2.4.0-snapshot versions so we can use them immediately with Docker as well.

---
This change is [Reviewable](https://reviewable.io/reviews/openhab/openhab-docker/172)

### CODE REVIEW

**Comment by kaikreuzer** [comment]
2.3.0 artifacts are available now, can this be merged? @wborn as it is labelled WIP, is there still anything open / to do?

**Comment by wborn** [comment]
This PR also builds a 2.4.0-SNAPSHOT container but it looks like the [openhab-2.4.0-SNAPSHOT.zip](https://openhab.ci.cloudbees.com/job/openHAB-Distribution/lastSuccessfulBuild/artifact/distributions/openhab/target/openhab-2.4.0-SNAPSHOT.zip) it is using is not yet available @kaikreuzer .

If it's not easy to create that now we can also remove the creation of the 2.4.0-snapshot container images temporarily from the matrix used by Travis in .travis.yml .

**Comment by kaikreuzer** [comment]
That's correct. I have just triggered the snapshot build, so let's see if we can make that easily available: https://openhab.ci.cloudbees.com/job/openHAB2-Bundles/348/

**Comment by wborn** [comment]
Thanks! I made a local build and it all seems to work now. :-)

**Comment by kaikreuzer** [comment]
So I'll merge?

**Comment by cniweb** [comment]
@wborn Thank you, for your PR!
I update the full description on Docker Hub ( https://hub.docker.com/r/openhab/openhab/ )

**Pull request merged**
