### PR TITLE
fixed broken build for arm64. migrated from ubuntu to debian jessie. …

### PR DESCRIPTION
**Pull request by legacycode**
fixed broken build for arm64. migrated from ubuntu to debian jessie image. migrated from oraclejdk to openjdk8. You can review the build at: https://travis-ci.org/legacycode/openhab2-docker/builds/191054020

Signed-off-by: Christian Lehmann <info@legacycode.org> (github: legacycode)

### CODE REVIEW

**Comment by cniweb** [comment]
@legacycode Is it obsolate with this PR #48 ?

**Comment by cniweb** [comment]
Travis Build for #48 failed:
https://travis-ci.org/openhab/openhab-docker/builds/191302447

**Comment by legacycode** [comment]
PR #47 (this one) is not obsolete. Build #48 faild, because this PR was not merged yet. This PR will fix the broken build.

**Comment by cniweb** [comment]
Thank!
I merged it.

**Comment by kaikreuzer** [comment]
> migrated from oraclejdk to openjdk8. 

Why has this been done? openHAB is not supported on OpenJDK - this PR will cause major issues.

**Comment by kaikreuzer** [comment]
@cniweb I would highly recommend to revert the change of the JDK.

**Comment by legacycode** [comment]
Hi. There where some issues using the ubuntu-debootstrap image together with gosu on arm64 architecture. With the change to debian-debootstrap i also used the debian backports of OpenJDK8. I did not find a apt-get repository for ARM64 Oracle. Do you think using the debian-debootstrap container will also cause major issues?

**Comment by legacycode** [comment]
If it is ok for you, i will try to install oracle jdk in debian-debootstrap and create a new PR. BTW: Could you give me more information, why OpenJDK will cause major issues? I would like to understand the problem in detail.

**Comment by kaikreuzer** [comment]
The main issue with OpenJDK on ARM is that it is terribly slow - I have seen startup times of 15-30 minutes (instead of 2-3 minutes with Oracle or Zulu JDK) - see e.g. [here](https://community.openhab.org/t/raspberry-pi-users-switch-to-oracle-jdk8-for-instant-speed-boost/12934).
Besides the performance, there are regularly bug reports of crashing JVMs related to OpenJDK, which do not appear on OracleJDK - just [search for OpenJDK in the forum](https://community.openhab.org/search?q=OpenJDK) and you will find many of those.

**Comment by legacycode** [comment]
Thanks. I am still working on moving back to Oracle. PR follows.

**Comment by kaikreuzer** [comment]
Alternatively, you could also directly try to go for https://github.com/openhab/openhab-docker/issues/26.
Although Zulu Embedded is an OpenJDK build, it runs very smooth as I mentioned in the issue.
It would be the preferred JVM for docker as it does not have any legal issues, whereas the are some doubts regarding the OracleJDK in this respect.

**Comment by legacycode** [comment]
Ok. I will give it a try.

**Comment by legacycode** [comment]
Could not get Zulu to run on ARM64 architecture. I created #49 to move back to Oracle in the meantime.

**Pull request merged**
