### PR TITLE
 Switch back to alpine v3.6

### PR DESCRIPTION
**Pull request by cniweb**
This change is [Reviewable](https://reviewable.io/reviews/openhab/openhab-docker/131)

### CODE REVIEW

**Comment by martinvw** [comment]
Does not start on my Docker on MacOs, do not have full remote access to my Ubuntu container host, so cannot run it there now.

**Comment by martinvw** [comment]
That is interesting --host is misbehaving on mac os

**Comment by martinvw** [comment]
Okay, the amd64-alpine works :-)

**Comment by smerschjohann** [comment]
This PR should fix #132, correct?

**Comment by wborn** [comment]
@smerschjohann 
I think this will also fix #132 because Travis [build 850 fails](https://travis-ci.org/openhab/openhab-docker/builds/318318594) on all alpine images whereas [build 851](https://travis-ci.org/openhab/openhab-docker/builds/318347629) of this PR succeeds. :+1:

**Comment by wborn** [comment]
After Googling a bit it looks like the root cause of this issue is that the CDN used by APK for latest-stable may still return old versions. I just tested building with `FROM multiarch/alpine:amd64-v3.7` and that also worked for me.

**Comment by cniweb** [comment]
I will first release alpine 3.6 and go to 3.7 in a later build.

**Pull request merged**
