### PR TITLE
Fixes #163 windows path issue

### LINKED ISSUE #163: Writing the backup tar may crash
The backup tar may crash on a vagrant running docker with mounted windows shares.

> windows host->vagrant guest->obenhab-docker

The reason for this is that colon is not allowed in a windos path. The tar will crash similar to this:

[root@localhost vagrant]# tar --exclude=/etc/openhab/userdata/backup -c -f /etc/openhab/userdata/backup/userdata-2018-03-18T22:35:56.tar /etc/openhab/userdata/
tar: /etc/openhab/userdata/backup/userdata-2018-03-18T22\:35\:56.tar: Cannot open: Protocol error
tar: Error is not recoverable: exiting now

The resolution might be to replace the ":" from the time with "-". This is not a nice way of formating time, but it works.

### PR DESCRIPTION
**Pull request by xrow**
Fixes #163 the windows path issue

Signed-off-by: Björn Dieding <bjoern@xrow.de> (github: xrow)

---
This change is [Reviewable](https://reviewable.io/reviews/openhab/openhab-docker/164)

### CODE REVIEW

**Comment by xrow** [comment]
Fixes #163

**Comment by cniweb** [comment]
Thanks @xrow but you must run the update.sh script after changing the entrypoint_alpine.sh and entrypoint_alpine.sh

**Comment by xrow** [comment]
I hope this is fine now. Please let me know.

**Comment by cniweb** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 40 of 40 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/openhab/openhab-docker/164#-:-L89dya7Eji49ZnS_Ks2:bnfp4nl)*

**Pull request merged**
