### PR TITLE
Add new command "console" to entrypoint.

### PR DESCRIPTION
**Pull request by cyberkov**
Hi!

I thought it might be interesting to access the console even when running the container as daemon in the background.
As the configuration is in the runtime folderfor now, I expect that there will be changes in the future how password and ssh-keys are going to be handled.

Cheers
Hannes

### CODE REVIEW

**Comment by LambdaDriver** [comment]
I think this is a great idea. Also, should make sure to update the documentation and include the default docker ctrl-p, ctrl-q detach command.

**Comment by cniweb** [comment]
I think the documentation (usage, etc.) should in the wiki of this project and not in the README.md.

**Comment by kaikreuzer** [comment]
No, I would prefer the README.md (or some other markdown files in the main repo), because this will allow us to integrate the docs in the upcoming aggregated openHAB documentation (see https://community.openhab.org/t/oh-2-documentation/6927)

**Comment by cniweb** [comment]
Oh, OK

**Comment by cniweb** [comment]
Hi @cyberkov,

I tested your image and it works!
Can I merge your PR?

The documentation we should generally outsource to a separate markdown file.

Chris

**Comment by cyberkov** [comment]
Hi Chris! 
Thanks for testing! Yes please. I think it make sense if at least four eyes check on changes as everything goes straight to the docker image :-) usually the code gets better as well when done in that way ;-)

Cheers Hannes

**Pull request merged**
