### PR TITLE
Add 2.4.0.M5 and update scripts for easier version management

### PR DESCRIPTION
**Pull request by wborn**
Adds the 2.4.0.M5 milestone build.

Versions for which Docker images are generated are now managed in a versions file.

The update.sh scripts now:
* calls update-docker-files.sh for generating Dockerfiles based on the versions
* calls update-travis-config.sh to generate .travis.yml based on the versions
* calls update-readme.sh to update versions specific content in the README.md file

Furthermore:
* When a new stable release is added to the versions file the old milestone and snapshot builds are automatically removed from the build and the new snapshot is added.
* The unused i386 images have been removed.
* Only builds for the last 3 milestone versions are generated.

---
This change is [Reviewable](https://reviewable.io/reviews/openhab/openhab-docker/200)

### CODE REVIEW

**Comment by wborn** [comment]
It would be awesome if you could review/merge this PR @cniweb!

**Comment by kaikreuzer** [comment]
Is there any way we could automate that release process?

**Comment by wborn** [comment]
We could improve update.sh and the entrypoint_alpine.sh, entrypoint_debian.sh scripts so they work better with future versions. Then if the pipeline would update the versions and run update.sh and commit the result, Travis CI could take over and do the more resource intensive parallel image building.

**Comment by wborn** [comment]
I've updated the scripts to further automate version management. 

Adding a new milestone or stable release should now be as simple as adding it to the `versions` file and running `update.sh` .

That should automatically update all files that are now manually updated. Then if the updated content is commited Travis will build the containers in parallel as it normally does. :smile: Building all containers could take more than 1 hour.

Could those steps be done in the pipeline when a new stable or milestone release is created @pfink?

The only manual remaining step would then be syncing the README.md to the [Docker Hub container description](https://hub.docker.com/r/openhab/openhab/).

**Comment by pfink** [comment]
@wborn: Sure. Could you post the exact command that should be added?

**Comment by wborn** [comment]
Thanks for merging @cniweb! :+1: 

Something like the following commands should work with Bash @pfink :

```bash
OH2_RELEASE_VERSION=2.4.0.M6

git clone git@github.com:openhab/openhab-docker.git .

echo "$OH2_RELEASE_VERSION" >> versions
./update.sh

git add .
git commit . -m "Adding $OH2_RELEASE_VERSION release"
git push
```

**Pull request merged**
