### PR TITLE
Docker image based on Alpine Linux

### PR DESCRIPTION
**Pull request by cniweb**

### CODE REVIEW

**Comment by cniweb** [comment]
Close #99

**Comment by martinvw** [comment]
I was only at file one with reviewing but that looked good 😉

**Comment by martinvw** [comment]
@cniweb do you think all users running snapshots realize that they will not be updated anymore because they have to pull another image / tag?

It had me in doubt for a while:

```
martinvw@elbrus:~$ docker pull openhab/openhab:2.2.0-snapshot-amd64
2.2.0-snapshot-amd64: Pulling from openhab/openhab
Digest: sha256:92d8ad4b2947b19e82b883f8dd0f4040e16ea7475558ad74e7754dfaa29ca9df
Status: Image is up to date for openhab/openhab:2.2.0-snapshot-amd64
martinvw@elbrus:~$ docker pull openhab/openhab:2.2.0-snapshot-amd64-debian
2.2.0-snapshot-amd64-debian: Pulling from openhab/openhab
e5b356725761: Pull complete 
16fbc193406b: Pull complete 
959e4b64c293: Pull complete 
a9dc74fa018c: Pull complete 
25de107891bf: Pull complete 
66fa18b5fd7a: Pull complete 
a68a8f15bc03: Pull complete 
cabcbe7b624b: Pull complete 
Digest: sha256:d64d803ef4c7fe3ba8a6db4f674a4f9701eaf3a1de7152017fa963e68139793a
Status: Downloaded newer image for openhab/openhab:2.2.0-snapshot-amd64-debian
```

wdyt? Should we put out a notice somewhere or can we make we either remove the old `openhab/openhab:2.2.0-snapshot-amd64` or let it somehow forward to `openhab/openhab:2.2.0-snapshot-amd64-debian`

**Comment by cniweb** [comment]
@martinvw Good point, I will remove the old tags

**Pull request merged**
