### PR TITLE
Fixed README section for accessing Karaf console

### PR DESCRIPTION
**Pull request by eschizoid**

### CODE REVIEW

**Comment by sjka** [comment]
At least for me, that's not working (I pulled the latest `openhab/openhab:amd64-online`image):
```
sjka@somehost:~$ docker exec -it openhab client
exec: "client": executable file not found in $PATH
```

However, this here works for me, which is btw what you suggested yourself in https://github.com/openhab/openhab-docker/issues/11#issuecomment-244840094:

```
sjka@somehost:~$ docker exec -it openhab /openhab/runtime/karaf/bin/client
client: Ignoring predefined value for KARAF_HOME
Logging in as openhab
[...]
```

So either the image needs to be fixed & updated first, or the documentation should follow whatever currently works.

**Comment by eschizoid** [comment]
@cyberkov What you wanna do, update the `$PATH` for the docker image or the documentation?

**Comment by eschizoid** [comment]
@sjka:
>So either the image needs to be fixed & updated first, or the documentation should follow whatever currently works.

README file updated

**Comment by sjka** [comment]
thanks, that works for me

**Pull request merged**
